class HtmlPatterns:
    div_patterns = [
        ["div", {"class": "cmp-text-editable"}],
        ["div", {"class": "courseDescription"}],
        # [],
    ]

    drop_page_titles = [
        "Privacy Statement English",
        "Talk to a sales representative",
        "UBS Global Technology Conference",
        "Autodesk Health Dashboard Status",
        "Terms of Use",
        "FISCAL",
        "使用規約",
    ]

    terminal_text = [
        "DOWNLOAD FREE TRIAL\n",
        "See also\n",
        "Have additional questions?\n",
        "Share this story\n",
        # "SHARE THIS STORY\n",#starting text
        "About the Author\n",
    ]

    bs_drop_text = [
        "Privacy | Do not sell or share my personal information | Cookie preferences | Report noncompliance | Terms of use | Legal | © 2023 Autodesk Inc. All rights reserved",
        "| autodesk",
        "© Copyright 2022 Autodesk Inc. All Rights Reserved.",
        "SIGN INNEW TO AUTODESK? CREATE ACCOUNT×",
        "\u200c",
        "AccountSign inSign outNavigationHomeSuccess PlanningCoursesPartner FinderFollow Us Facebook Instagram Twitter LinkedinHelp and SupportAutodesk Knowledge NetworkContact SupportTerms of UsePrivacy settingsPrivacy/CookieLegalTerms of Use Privacy settings|Privacy/Cookies",
        "Support and software access",
        "Technical support Autodesk support specialists: Schedule a call,† chat online (limited availability), or email us.",
        "Remote desktop assistance: Get secure, hands-on troubleshooting.†",
        "Online resources: Access our knowledge base for help documentation, tutorials, training videos, and community support forums.",
        "Access to the latest software: Instantly access the newest releases and updates. ",
        "Access previous versions: Download and use previous releases. Flexible term lengths: Subscribe monthly, annually, or for 3 years.* Administrative tools: Easily manage software licenses, seats, and usage from your Autodesk Account. *Not available to maintenance plan customers. **As with all performance tests, results may vary based on user experience, machine, operating system, filters, and even source material. While every effort has been made to make the tests as fair and objective as possible, your results may differ. Product information and specifications are subject to change without notice. Autodesk provides this information “as is,” without warranty of any kind, either express or implied.",
        "\nAutodesk\n\nHow to buy\nSupport\n\nPrivacy",
        "You need to enable JavaScript to run this app.",
        "icon-svg-checkout-check-circle-outline",
    ]

    inscriptis_drop_text = [
        " . ",
        " * ",
        " + ",
        " o ",
        "  |  ",
        "icon-svg-checkout-check-circle-outline",
        "See more FAQ\n",
        "See less FAQ\n",
        "Trust Center\n",
        "Foundation\n",
        "Research\n",
        "Insights\n",
        "This app works best with JavaScript enabled.",
        "You need to enable JavaScript to run this app.",
        "Account\n",
        "Sign in\n",
        "Sign In",
        "Sign out\n",
        "Sign Out",
        "Navigation\n",
        "Home\n",
        "Success Planning\n",
        "Courses\n",
        "Partner Finder\n",
        "Follow Us\n",
        "Facebook\n",
        "Instagram\n",
        "Twitter\n",
        "Linkedin\n",
        "Help and Support\n",
        "Autodesk Knowledge Network\n",
        "Contact Support\n",
        "Terms of Use.\n",
        "Terms of Use\n",
        "Privacy settings",
        "Privacy/Cookie",
        "Legal\n",
        "All plans are subject to terms and conditions. Please see Standard and Premium.",
        "Terms of Use Privacy settings | Privacy/Cookies | Legal\n",
        "© Copyright 2023 Autodesk Inc.",
        "© Copyright 2023 Autodesk Inc",
        "© Copyright 2022 Autodesk Inc.",
        "© Copyright 2022 Autodesk Inc",
        "All Rights Reserved.",
        "All Rights Reserved",
        "All plans are subject to terms and conditions. Please see Standard and Premium. © Copyright 2022 Autodesk Inc. All Rights Reserved.",
        "Learn more\n",
        "Autodesk\n",
        "Company overview\n",
        "Careers\n",
        "Investor relations\n",
        "Autodesk Trust Center\n",
        "Newsroom\n",
        "Diversity and belonging\n",
        "Autodesk Foundation\n",
        "Sustainability\n",
        "Contact us\n",
        "Students and educators\n",
        "Affiliate program\n",
        "Autodesk Research\n",
        "Autodesk Insights\n",
        "How to buy\n",
        "View all products\n",
        "Buying with Autodesk\n",
        "Renewal options\n",
        "Find a reseller\n",
        "Sales and refunds\n",
        "Choose your subscription plan",
        "Pay as you go with Flex\n",
        "Support\n",
        "Product support\n",
        "Manage your account\n",
        "Download and install software\n",
        "COVID-19 resources\n",
        "Education support\n",
        "Contact support\n",
        "Privacy | Do not sell or share my personal information | Cookie preferences | Report noncompliance | Terms of use | Legal | © 2023 Autodesk Inc. All rights reserved",
        # "BIM overview\n",
        # "BIM solutions\n",
        # "Architecture\n",
        # "Civil\n",
        # "MEP\n",
        # "Structural\n",
        # "Plant\n",
        # "Construction\n",
        # "BIM interoperability\n",
        # "Software\n",
        # "AEC Collection\n",
        # "Revit\n",
        # "BIM Collaborate Pro\n",
        # "Civil 3D\n",
        # "Recap Pro\n",
        "Docs\n",
        # "Insight\n",
        # "3ds Max\n",
        # "Build\n",
        # "Assemble\n",
        # "BuildingConnected\n",
        "Back\n"
        # "BIM for Architecture\n",
        "See it with BIM",
        "Products and services\n",
        "Product updates\n",
        "Trials\n",
        "My profile and settings\n",
        "Password and security\n",
        "Language\n",
        "Communications\n",
        "Product privacy\n",
        "My Community\n",
        "Community profile\n",
        "Contributions\n",
        "Forum preferences\n",
        "Need help? Ask the Autodesk Assistant!\n",
        "The Assistant can help you find answers or contact an agent.\n",
        "Ask the Assistant\n",
        "What level of support do you have?\n",
        "Different subscription plans provide distinct categories of support. Find out the level of support for your plan.\n",
        "View levels of support\n",
    ]
